version: "3"
services:
  db:
    container_name: db
    image: postgres:latest
    ports: 
      - "5432:5432"
    environment:
        POSTGRES_HOST_AUTH_METHOD: trust  
    volumes:
      - my_hw_dbdata:/var/lib/postgresql/data
    restart: always